on:
  pull_request:
    types: [opened, synchronize]
jobs:
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: ESLint
        uses: betrybe/eslint-linter-action@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  stylelint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: Stylelint
        uses: betrybe/stylelint-linter-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    needs: [eslint]
    services:
      mongodb:
        image: mongo
        ports:
          - "27017:27017"
        options: -v ${{ github.workspace }}:/github/workspace
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
          - 33060:33060
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:	
          node-version: '12'
      - name: Evaluator step
        id: evaluator
        uses: betrybe/cypress-evaluator-action@v5
        with:
          repository-test-name: 'betrybe/sd-0x-project-trybeer-v2-tests'
          repository-test-branch: 'main'
          npm-start: true
        env:
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'password'
          HOSTNAME: 'mysql'
          DB_URL: 'mongodb://mongodb:27017/Trybeer'
          SCHEMA: 'Trybeer'
          DB_NAME: 'Trybeer'
          GITHUB_USER: ${{ github.actor }}
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.number }}
